version: 0.0
os: windows
files:
  - source: testdirectory\index.html
    destination: c:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: iisapp\before-install.bat
      timeout: 900
      
  ApplicationStop:
    - location: iisapp\application-stop.bat
      timeout: 900
